/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1git.UI;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import practica1git.Archivos.Archivos;
import practica1git.Backend.Estudiante;
import practica1git.Backend.Libro;
import practica1git.Backend.Prestamo;

/**
 *
 * @author jessiel
 */
public class Importaciones extends javax.swing.JDialog {
    
    File archivo;
    int contadorLibro;
    int contadorEstudiante;
    int contadorPrestamo;
    Archivos archivos;
    int registrosIgnorados;
    

    /**
     * Creates new form Impotaciones
     */
    public Importaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        unDiseño();
        buscadorArchivo = new JFileChooser();
        archivos = new Archivos();
    }

    Importaciones(VentanaPrincipal aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImportarDatos = new javax.swing.JLabel();
        btnAbrirArchivo = new javax.swing.JButton();
        btnImportarDatos = new javax.swing.JButton();
        lblTexto = new javax.swing.JLabel();
        lblArchivoAImportar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(206, 234, 123));
        setForeground(new java.awt.Color(201, 132, 132));

        lblImportarDatos.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblImportarDatos.setText("IMPORTAR DATOS");

        btnAbrirArchivo.setText("Abrir Archivo");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });

        btnImportarDatos.setText("IMPORTAR DATOS");
        btnImportarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarDatosActionPerformed(evt);
            }
        });

        lblTexto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblTexto.setText("ARCHIVO A IMPORTAR:");

        lblArchivoAImportar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblArchivoAImportar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImportarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblArchivoAImportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImportarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImportarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btnAbrirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArchivoAImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTexto))
                .addGap(47, 47, 47)
                .addComponent(btnImportarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed
        // TODO add your handling code here:
        //buscadorArchivo.showDialog(this, "ABRIR ARCHIVO");
        if (buscadorArchivo.showDialog(this, "Seleccionar")==JFileChooser.APPROVE_OPTION) {
            archivo = buscadorArchivo.getSelectedFile();
            lblArchivoAImportar.setText(archivo.getName());
        }
    }//GEN-LAST:event_btnAbrirArchivoActionPerformed

    private void btnImportarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarDatosActionPerformed
        // TODO add your handling code here:
        importarDatos(archivo);
    }//GEN-LAST:event_btnImportarDatosActionPerformed

    private void unDiseño(){
        setLocation(400,100);
        setBackground(Color.CYAN);
    }
    
    public void importarDatos( File archivoTXT ){
        
        try {
            FileReader lector = new FileReader(archivoTXT);
            BufferedReader buferLector = new BufferedReader(lector);
            String fila;
            
            while ((fila=buferLector.readLine())!=null) {                
                System.out.println(" "+fila);
                
                if(fila.contains("LIBRO")){
                    //guardarlibro  
                    System.out.println("ES LIBRO");
                    Libro libro = new Libro();
                    libro.setTitulo(cortarTituloLibro(buferLector.readLine()));
                    libro.setAutor(cortarAutorLibro(buferLector.readLine()));
                    libro.setCodigo(cortarCodigoLibro(buferLector.readLine()));
                    libro.setCantidad(cortarCantidadLibro(buferLector.readLine()));
                    archivos.guardarLibro(libro);
                    
                }else if(fila.contains("ESTUDIANTE")){
                    System.out.println("ES ESTUDIANTE");
                    //guardarestudiante
                    Estudiante estudiante = new Estudiante();
                    estudiante.setCarnet(cortarCarnetEstudiante(buferLector.readLine()));
                    estudiante.setNombre(cortarNombreEstudiante(buferLector.readLine()));
                    estudiante.setCodigoCarrera(cortarCodigoCarrera(buferLector.readLine()));
                    archivos.guardarEstudiante(estudiante);
                    
                }else if(fila.contains("PRESTAMO")){
                    System.out.println("ES PRESTAMO");
                    //guardarprestamo
                    Prestamo prestamo = new Prestamo();
                    prestamo.setCodigoLibro(cortarCodigoLibro(buferLector.readLine()));
                    prestamo.setCarnet(cortarCarnetEstudiante(buferLector.readLine()));
                    prestamo.setFechaPrestamo(cortarFechaPrestamo(buferLector.readLine()));
                    archivos.GuardarPrestamo(prestamo);
                    
                }else{
                    //guardarregistroignorado
                    registrosIgnorados++;
                    
                }
                
            }
            
            JOptionPane.showMessageDialog(this, registrosIgnorados );

                
            
        } catch (Exception e) {
        }
    }
    
    
    public String cortarTituloLibro(String titulo){
        String nuevaString=titulo.substring(7, titulo.length()-1);
        return nuevaString;
    }
    
    public String cortarAutorLibro(String autor){
        String nuevaString=autor.substring(7, autor.length()-1);
        return nuevaString;
    }
    
    public String cortarCodigoLibro(String codigo){
        String nuevaString=codigo.substring(8, codigo.length()-1);
        return nuevaString;
    }
    
    public String cortarCodigoLibro2(String codigo){
        String nuevaString=codigo.substring(12, codigo.length()-1);
        return nuevaString;
    }
    
    public int cortarCantidadLibro(String cantidad){
        int nuevacantidad=Integer.parseInt(cantidad.substring(9));
        return nuevacantidad;
    }
    
    public int cortarCarnetEstudiante(String carnet){
        int nuevacantidad=Integer.parseInt(carnet.substring(7,carnet.length()-1));
        return nuevacantidad;
    }
    
    public String cortarNombreEstudiante(String nombre){
        String nuevaString=nombre.substring(7, nombre.length()-1);
        return nuevaString;
    }
    
    public int cortarCodigoCarrera(String carrera){
        int nuevacantidad=Integer.parseInt(carrera.substring(8));
        return nuevacantidad;
    }
    
    public String cortarFechaPrestamo(String fecha){
        String nuevaString=fecha.substring(7, fecha.length()-1);
        return nuevaString;
    }
    
    
    
    
    private JFileChooser buscadorArchivo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnImportarDatos;
    private javax.swing.JLabel lblArchivoAImportar;
    private javax.swing.JLabel lblImportarDatos;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
