
package practica1git.UI;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import practica1git.Backend.Estudiante;
import practica1git.Backend.Prestamo;

/**
 *
 * @author astridmc
 */
public class RegistrarDevolucion extends javax.swing.JDialog {

    Prestamo prestamo;
    private int verificador;
    private LocalDate fechaActual;
    private Estudiante estudiante;
    public RegistrarDevolucion(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCarnet = new javax.swing.JLabel();
        txtCdNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCdLetra = new javax.swing.JTextField();
        txtNoCarnet = new javax.swing.JTextField();
        btnAgregarOtroLibro = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCalcularSaldo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(219, 253, 235));

        tituloLbl.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        tituloLbl.setText("REGISTRAR DEVOLUCION");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("****************************");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("INGRESE CODIGO DEL LIBRO  EJ: 123  -    ABC");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 35)); // NOI18N
        jLabel8.setText("-");

        lblCarnet.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCarnet.setText("INGRESE CARNET DEL ALUMNO:");

        txtCdNumero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCdNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCdNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCdNumeroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("NOMBRE ALUMNO:");

        txtCdLetra.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCdLetra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCdLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCdLetraActionPerformed(evt);
            }
        });

        txtNoCarnet.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNoCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoCarnetActionPerformed(evt);
            }
        });

        btnAgregarOtroLibro.setText("Agregar otro libro");
        btnAgregarOtroLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarOtroLibroActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCalcularSaldo.setText("CALCULAR SALDO");
        btnCalcularSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularSaldoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("EL TOTAL A PAGAR ES:   ");

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(146, 7, 7));
        lblTotal.setText("Q.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(tituloLbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(61, 61, 61)
                                            .addComponent(btnAgregarOtroLibro)
                                            .addGap(33, 33, 33)
                                            .addComponent(txtCdNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCdLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(229, 229, 229)
                                        .addComponent(btnCalcularSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addGap(210, 210, 210))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(lblCarnet))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(txtNoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl)
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCdLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCdNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarOtroLibro)))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(lblCarnet)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(329, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCdNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCdNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCdNumeroActionPerformed

    private void txtCdLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCdLetraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCdLetraActionPerformed

    private void txtNoCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoCarnetActionPerformed

    private void btnAgregarOtroLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarOtroLibroActionPerformed
 
    }//GEN-LAST:event_btnAgregarOtroLibroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        validarCarnet();
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCalcularSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularSaldoActionPerformed
        validarDatos();
    }//GEN-LAST:event_btnCalcularSaldoActionPerformed

    
    
    private void validarDatos(){
        prestamo = new Prestamo();
        verificador =0;
        
        if(verificador ==0){
            validarCarnet();
            if(verificador == 2){
                validarCodigo();
                if (verificador ==2){
                    camposVacios();
                    if(verificador ==2){
                        vaciarCampos();
                        estudiante.calcularSaldo(estudiante, fechaActual);
                    }
                }
            }    
        }
    }
    
    private void vaciarCampos(){
        if(verificador==0){
            txtNoCarnet.setText("");
        }
        txtCdLetra.setText("");
        txtCdNumero.setText("");
    }
    
      public int codigoNumero;
    public int codigoLetra;
    
    private void validarCodigo(){
        if(txtCdNumero.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"codigo Obligatorio");
            verificador =1;
        }else if(!txtCdNumero.getText().isEmpty()){
            verificador =2;
        }
        if(txtCdLetra.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"codigo Obligatorio");
            verificador =1;
        }else  if(!txtCdLetra.getText().isEmpty()){
            verificador =2;
        }
        
        
        try{
            codigoNumero = Integer.parseInt(txtCdNumero.getText());
            if(txtCdNumero.getText().length() != 3  ){
                JOptionPane.showMessageDialog(null,"codigo numerico no valido");
                verificador =1;
            }else  if(txtCdNumero.getText().length() != 3  ){
                verificador =2;
            }
    	}catch(NumberFormatException ex){
        	JOptionPane.showMessageDialog(null,"Codigo No es un  numero");
                verificador =1;
    	}
        
        try{
            codigoLetra = Integer.parseInt(txtCdLetra.getText());
            JOptionPane.showMessageDialog(null,"codigo alfavetico no es letra");
            verificador =1;
    	}catch(NumberFormatException ex){
            if(txtCdLetra.getText().length() != 3  ){
                JOptionPane.showMessageDialog(null,"codigo alfavetico de 3 caracteres");
                verificador =1;
            }else if (txtCdLetra.getText().length() == 3  ){
                 verificador =2;
            }
    	} 
    }
        
   public int carnet;
   
    private void validarCarnet(){
        try{
        	carnet = Integer.parseInt(txtNoCarnet.getText());
            if (txtNoCarnet.getText().length() !=9){
                JOptionPane.showMessageDialog(null,"carnet requiere 9 digitos");
                 verificador =1;
            } else if (txtNoCarnet.getText().length()==9){
                verificador =2;
                
            }
    	}catch(NumberFormatException ex){
        	JOptionPane.showMessageDialog(null,"Carnet invalido");
                 verificador =1;
        }
    }
    
     private void camposVacios(){
        if(txtNoCarnet.getText().isEmpty()){
            verificador =1;
            JOptionPane.showMessageDialog(null,"codigo Requerido");
        }else if(!txtNoCarnet.getText().isEmpty()){
            verificador = 2;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarOtroLibro;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalcularSaldo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JTextField txtCdLetra;
    private javax.swing.JTextField txtCdNumero;
    private javax.swing.JTextField txtNoCarnet;
    // End of variables declaration//GEN-END:variables
}
